-- ==============================================================================
-- ARDYN - CONSOLIDATED SAFE & IDEMPOTENT MIGRATION SCRIPT
-- ==============================================================================
-- NOTA DE SEGURIDAD / INTEGRIDAD:
-- Este script es 100% ADITIVO e IDEMPOTENTE.
-- NO CONTIENE: DROP TABLE, DROP COLUMN, TRUNCATE, DELETE.
-- Respeta y preserva íntegramente las tablas existentes en la base de datos
-- (como salus_visitas, pacientes, nutri_profiles, etc.).
-- ==============================================================================

-- Habilitar extensión pgcrypto si no está disponible (para gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 1. TABLAS CORE / CLIENTES / TRANSACCIONES
-- ==============================================================================

-- 1.1 USERS (Clientes del sistema)
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id text,
  name text,
  last_load_date text,
  observations text,
  phone text UNIQUE,
  user_password text,
  user_view boolean DEFAULT true,
  user_photo text,
  user_profile text DEFAULT 'CLIENT',
  user_status boolean DEFAULT true,
  coin_balance bigint DEFAULT 0,
  image_url text,
  debt_balance numeric DEFAULT 0.0
);

-- 1.2 SALES (Ventas / Ingresos)
CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  legacy_id text,
  date timestamp,
  observations text,
  amount numeric DEFAULT 0.0,
  branch text,
  month_number integer
);

-- 1.3 EXPENSES (Egresos / Gastos)
CREATE TABLE IF NOT EXISTS public.expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  legacy_id text,
  date timestamp,
  category text,
  amount numeric DEFAULT 0.0,
  observations text,
  branch text
);

-- 1.4 COIN TRANSACTIONS (Puntos / Monedas de fidelización)
CREATE TABLE IF NOT EXISTS public.coin_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  client_name text,
  amount numeric DEFAULT 0.0,
  coins_added integer DEFAULT 0,
  date timestamp DEFAULT timezone('utc'::text, now()),
  notification_status text,
  notification_error text
);

-- 1.5 DEBT TRANSACTIONS (Cuenta Corriente)
CREATE TABLE IF NOT EXISTS public.debt_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  client_id bigint REFERENCES public.users(id) ON DELETE CASCADE,
  client_name text,
  amount numeric DEFAULT 0.0,
  transaction_type text NOT NULL CHECK (transaction_type IN ('charge', 'payment')),
  balance_after numeric DEFAULT 0.0,
  date timestamp DEFAULT timezone('utc'::text, now()),
  notes text,
  notification_status text,
  notification_error text
);

-- ==============================================================================
-- 2. TABLAS E-COMMERCE / CATÁLOGO / VENTAS
-- ==============================================================================

-- 2.1 RUBROS
CREATE TABLE IF NOT EXISTS public.rubros (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  icono text,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.2 CATEGORÍAS
CREATE TABLE IF NOT EXISTS public.categorias (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  imagen_url text,
  rubro_id uuid REFERENCES public.rubros(id) ON DELETE CASCADE,
  orden integer DEFAULT 0,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.3 MARCAS
CREATE TABLE IF NOT EXISTS public.marcas (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL,
  logo_url text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.4 LISTAS DE PRECIOS
CREATE TABLE IF NOT EXISTS public.listas_precios (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  tipo text DEFAULT 'markup' CHECK (tipo IN ('markup', 'escalonada')),
  markup numeric DEFAULT 1.0,
  activo boolean DEFAULT true,
  es_default boolean DEFAULT false,
  es_default_minorista boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.5 ESCALONES DE LISTA DE PRECIOS
CREATE TABLE IF NOT EXISTS public.lista_precio_escalones (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  lista_id uuid REFERENCES public.listas_precios(id) ON DELETE CASCADE NOT NULL,
  cantidad_minima integer NOT NULL DEFAULT 1,
  multiplicador numeric NOT NULL DEFAULT 1.0,
  orden integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.6 PRODUCTOS
CREATE TABLE IF NOT EXISTS public.productos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre text NOT NULL,
  descripcion text,
  sku text,
  external_id text,
  precio_costo numeric DEFAULT 0.0,
  precio_mayorista numeric DEFAULT 0.0,
  precio_unitario numeric DEFAULT 0.0,
  stock integer DEFAULT 0,
  cantidad_minima integer DEFAULT 1,
  categoria_id uuid REFERENCES public.categorias(id) ON DELETE SET NULL,
  marca_id uuid REFERENCES public.marcas(id) ON DELETE SET NULL,
  lista_precio_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL,
  lista_precio_minorista_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL,
  lista_escalonada_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL,
  lista_escalonada_minorista_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL,
  imagenes jsonb DEFAULT '[]'::jsonb,
  variantes jsonb DEFAULT '[]'::jsonb,
  activo boolean DEFAULT true,
  activo_mayorista boolean DEFAULT true,
  activo_minorista boolean DEFAULT true,
  destacado boolean DEFAULT false,
  en_oferta boolean DEFAULT false,
  precio_oferta numeric DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.7 PROMOCIONES POR PRODUCTO
CREATE TABLE IF NOT EXISTS public.producto_promociones (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  producto_id uuid REFERENCES public.productos(id) ON DELETE CASCADE NOT NULL,
  nombre text NOT NULL,
  tipo text DEFAULT 'markup' CHECK (tipo IN ('markup', 'precio_fijo', 'descuento')),
  valor numeric NOT NULL DEFAULT 0.0,
  cantidad_minima integer DEFAULT 1,
  activo boolean DEFAULT true,
  fecha_inicio timestamp with time zone,
  fecha_fin timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.8 PEDIDOS
CREATE TABLE IF NOT EXISTS public.pedidos (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  numero_pedido serial,
  cliente_nombre text NOT NULL,
  cliente_email text,
  cliente_telefono text NOT NULL,
  estado text DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'procesando', 'completado', 'cancelado')),
  total numeric DEFAULT 0.0,
  notas text,
  notificado_whatsapp boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.9 PEDIDO ITEMS
CREATE TABLE IF NOT EXISTS public.pedido_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  pedido_id uuid REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
  producto_id uuid REFERENCES public.productos(id) ON DELETE SET NULL,
  producto_nombre text NOT NULL,
  cantidad integer NOT NULL DEFAULT 1,
  precio_unitario numeric NOT NULL DEFAULT 0.0,
  subtotal numeric NOT NULL DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.10 COMPRAS A PROVEEDOR
CREATE TABLE IF NOT EXISTS public.compras (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  proveedor text,
  numero_factura text,
  notas text,
  total numeric DEFAULT 0.0,
  estado text DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'confirmada', 'cancelada')),
  fecha timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.11 COMPRA ITEMS
CREATE TABLE IF NOT EXISTS public.compra_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  compra_id uuid REFERENCES public.compras(id) ON DELETE CASCADE NOT NULL,
  producto_id uuid REFERENCES public.productos(id) ON DELETE SET NULL,
  producto_nombre text NOT NULL,
  cantidad integer NOT NULL DEFAULT 1,
  precio_unitario numeric NOT NULL DEFAULT 0.0,
  precio_anterior numeric(10, 2),
  subtotal numeric NOT NULL DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2.12 CONFIGURACIONES
CREATE TABLE IF NOT EXISTS public.configuraciones (
  clave text PRIMARY KEY,
  valor jsonb NOT NULL,
  descripcion text,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- 3. GARANTIZAR COLUMNAS ADICIONALES (POR SI LA TABLA YA EXISTÍA)
-- ==============================================================================

ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS external_id text;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS precio_costo numeric DEFAULT 0.0;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS precio_mayorista numeric DEFAULT 0.0;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS precio_unitario numeric DEFAULT 0.0;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS cantidad_minima integer DEFAULT 1;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS lista_precio_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS lista_precio_minorista_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS lista_escalonada_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS lista_escalonada_minorista_id uuid REFERENCES public.listas_precios(id) ON DELETE SET NULL;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS activo_mayorista boolean DEFAULT true;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS activo_minorista boolean DEFAULT true;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS en_oferta boolean DEFAULT false;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS precio_oferta numeric DEFAULT 0.0;
ALTER TABLE public.productos ADD COLUMN IF NOT EXISTS variantes jsonb DEFAULT '[]'::jsonb;

ALTER TABLE public.listas_precios ADD COLUMN IF NOT EXISTS es_default_minorista boolean DEFAULT false;
ALTER TABLE public.compra_items ADD COLUMN IF NOT EXISTS precio_anterior numeric(10, 2);
ALTER TABLE public.coin_transactions ADD COLUMN IF NOT EXISTS notification_status text;
ALTER TABLE public.coin_transactions ADD COLUMN IF NOT EXISTS notification_error text;
ALTER TABLE public.debt_transactions ADD COLUMN IF NOT EXISTS notification_status text;
ALTER TABLE public.debt_transactions ADD COLUMN IF NOT EXISTS notification_error text;

-- ==============================================================================
-- 4. ÍNDICES DE ALTO RENDIMIENTO
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_productos_categoria ON public.productos(categoria_id);
CREATE INDEX IF NOT EXISTS idx_productos_marca ON public.productos(marca_id);
CREATE INDEX IF NOT EXISTS idx_productos_activo ON public.productos(activo);
CREATE INDEX IF NOT EXISTS idx_productos_destacado ON public.productos(destacado);
CREATE INDEX IF NOT EXISTS idx_productos_external_id ON public.productos(external_id);
CREATE INDEX IF NOT EXISTS idx_productos_activo_mayorista ON public.productos(activo_mayorista);
CREATE INDEX IF NOT EXISTS idx_productos_activo_minorista ON public.productos(activo_minorista);
CREATE INDEX IF NOT EXISTS idx_productos_lista_escalonada_id ON public.productos(lista_escalonada_id);
CREATE INDEX IF NOT EXISTS idx_productos_lista_escalonada_minorista_id ON public.productos(lista_escalonada_minorista_id);
CREATE INDEX IF NOT EXISTS idx_productos_nombre ON public.productos USING gin(to_tsvector('spanish', nombre));

CREATE INDEX IF NOT EXISTS idx_categorias_rubro ON public.categorias(rubro_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido ON public.pedido_items(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON public.pedidos(estado);
CREATE INDEX IF NOT EXISTS idx_compra_items_compra ON public.compra_items(compra_id);
CREATE INDEX IF NOT EXISTS idx_compras_estado ON public.compras(estado);
CREATE INDEX IF NOT EXISTS idx_compras_fecha ON public.compras(fecha);
CREATE INDEX IF NOT EXISTS idx_listas_precios_activo ON public.listas_precios(activo);
CREATE INDEX IF NOT EXISTS idx_lista_escalones_lista ON public.lista_precio_escalones(lista_id);
CREATE INDEX IF NOT EXISTS idx_producto_promos_producto ON public.producto_promociones(producto_id);
CREATE INDEX IF NOT EXISTS idx_producto_promos_activo ON public.producto_promociones(activo);
CREATE INDEX IF NOT EXISTS idx_debt_transactions_client_id ON public.debt_transactions(client_id);
CREATE INDEX IF NOT EXISTS idx_debt_transactions_date ON public.debt_transactions(date DESC);
CREATE INDEX IF NOT EXISTS idx_debt_transactions_type ON public.debt_transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_coin_transactions_client ON public.coin_transactions(client_id);

-- ==============================================================================
-- 5. ROW LEVEL SECURITY (RLS) & POLÍTICAS
-- ==============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coin_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.debt_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rubros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marcas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compra_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listas_precios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lista_precio_escalones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuraciones ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso
DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Enable flow for anon" ON public.users;
  CREATE POLICY "Enable flow for anon" ON public.users FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable flow for anon" ON public.sales;
  CREATE POLICY "Enable flow for anon" ON public.sales FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable flow for anon" ON public.expenses;
  CREATE POLICY "Enable flow for anon" ON public.expenses FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable flow for anon" ON public.coin_transactions;
  CREATE POLICY "Enable flow for anon" ON public.coin_transactions FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable flow for anon" ON public.debt_transactions;
  CREATE POLICY "Enable flow for anon" ON public.debt_transactions FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.rubros;
  CREATE POLICY "Enable all for anon" ON public.rubros FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.categorias;
  CREATE POLICY "Enable all for anon" ON public.categorias FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.marcas;
  CREATE POLICY "Enable all for anon" ON public.marcas FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.productos;
  CREATE POLICY "Enable all for anon" ON public.productos FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.pedidos;
  CREATE POLICY "Enable all for anon" ON public.pedidos FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.pedido_items;
  CREATE POLICY "Enable all for anon" ON public.pedido_items FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.compras;
  CREATE POLICY "Enable all for anon" ON public.compras FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.compra_items;
  CREATE POLICY "Enable all for anon" ON public.compra_items FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.listas_precios;
  CREATE POLICY "Enable all for anon" ON public.listas_precios FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.lista_precio_escalones;
  CREATE POLICY "Enable all for anon" ON public.lista_precio_escalones FOR ALL USING (true);

  DROP POLICY IF EXISTS "Enable all for anon" ON public.producto_promociones;
  CREATE POLICY "Enable all for anon" ON public.producto_promociones FOR ALL USING (true);

  DROP POLICY IF EXISTS "Lectura pública de configuraciones" ON public.configuraciones;
  CREATE POLICY "Lectura pública de configuraciones" ON public.configuraciones FOR SELECT USING (true);

  DROP POLICY IF EXISTS "Permitir escritura configuraciones" ON public.configuraciones;
  CREATE POLICY "Permitir escritura configuraciones" ON public.configuraciones FOR ALL USING (true);
END $$;

-- ==============================================================================
-- 6. CONFIGURACIONES INICIALES (ARDYN BRANDING)
-- ==============================================================================

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'marquesina_minorista',
    '{"activo": true, "mensajes": ["10% Off en pagos en efectivo o transferencia.", "Hasta 3 cuotas sin interés con todas las tarjetas."]}'::jsonb,
    'Configuración de la cinta animada superior de la tienda minorista'
) ON CONFLICT (clave) DO NOTHING;

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'marquesina_mayorista',
    '{"activo": false, "mensajes": ["Envíos a todo el país", "Compra mínima $50.000"]}'::jsonb,
    'Configuración de la cinta animada superior de la tienda mayorista'
) ON CONFLICT (clave) DO NOTHING;

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'tienda_hero_mayorista',
    '{
      "titulo": "Catálogo Mayorista 📦",
      "descripcion": "Precios directos para revendedores y comercios.",
      "subtexto": "📦 Solo se muestran productos con stock disponible",
      "imagen_fondo_url": "/bg-hero.webp",
      "video_activo": false
    }'::jsonb,
    'Banner hero de la tienda mayorista'
) ON CONFLICT (clave) DO NOTHING;

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'tienda_hero_minorista',
    '{
      "titulo": "Tienda Oficial Ardyn 🛒",
      "descripcion": "Suplementos, indumentaria y accesorios deportivos de primera calidad.",
      "subtexto": "📦 Solo se muestran productos con stock disponible",
      "imagen_fondo_url": "/bg-hero.webp",
      "video_activo": false
    }'::jsonb,
    'Banner hero de la tienda minorista'
) ON CONFLICT (clave) DO NOTHING;

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'tienda_footer',
    '{
      "direccion": "📍 Av. Libertador 4858 Oeste, Rivadavia, San Juan",
      "telefono": "📱 +54 9 264 679-6509",
      "instagram": "@ardyn_oficial",
      "texto_creditos": "Ardyn E-commerce & Management",
      "url_creditos": "#"
    }'::jsonb,
    'Datos del footer de la tienda'
) ON CONFLICT (clave) DO NOTHING;

INSERT INTO public.configuraciones (clave, valor, descripcion)
VALUES (
    'tienda_whatsapp',
    '{
      "numero_mayorista": "5492645438114",
      "numero_minorista": "5492645438114",
      "mensaje_mayorista": "Hola Ardyn! Quiero hacer un pedido mayorista 🛒",
      "mensaje_minorista": "Hola Ardyn!",
      "mensaje_consulta": "Hola Ardyn! Tengo una consulta",
      "boton_flotante_activo": true
    }'::jsonb,
    'Números de WhatsApp y mensajes predeterminados'
) ON CONFLICT (clave) DO NOTHING;

-- ==============================================================================
-- 7. SUPABASE STORAGE (BUCKET "productos")
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'productos',
  'productos',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

DO $$ 
BEGIN
  DROP POLICY IF EXISTS "Imagenes productos publicas" ON storage.objects;
  CREATE POLICY "Imagenes productos publicas" ON storage.objects
    FOR SELECT USING (bucket_id = 'productos');

  DROP POLICY IF EXISTS "Permitir subir imagenes productos" ON storage.objects;
  CREATE POLICY "Permitir subir imagenes productos" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'productos');

  DROP POLICY IF EXISTS "Permitir actualizar imagenes productos" ON storage.objects;
  CREATE POLICY "Permitir actualizar imagenes productos" ON storage.objects
    FOR UPDATE USING (bucket_id = 'productos');

  DROP POLICY IF EXISTS "Permitir eliminar imagenes productos" ON storage.objects;
  CREATE POLICY "Permitir eliminar imagenes productos" ON storage.objects
    FOR DELETE USING (bucket_id = 'productos');
END $$;
